"""create paths and coordinates table

Revision ID: 5df23bcb071d
Revises: 
Create Date: 2025-11-10 21:55:39.292729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df23bcb071d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordinates',
    sa.Column('lat', sa.Numeric(precision=9, scale=7), nullable=False),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paths',
    sa.Column('pickup_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pickup_id'], ['coordinates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dropoff_coordinates',
    sa.Column('coordinates_id', sa.UUID(), nullable=True),
    sa.Column('path_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['coordinates_id'], ['coordinates.id'], ),
    sa.ForeignKeyConstraint(['path_id'], ['paths.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dropoff_coordinates')
    op.drop_table('paths')
    op.drop_table('coordinates')
    # ### end Alembic commands ###
