"""using fk as pk in association table dropoff

Revision ID: d8e509853035
Revises: 5df23bcb071d
Create Date: 2025-11-12 16:11:37.641498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e509853035'
down_revision: Union[str, Sequence[str], None] = '5df23bcb071d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dropoff_coordinates', 'coordinates_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('dropoff_coordinates', 'path_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dropoff_coordinates', 'path_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('dropoff_coordinates', 'coordinates_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
