FROM python:3.13-alpine AS builder

COPY --from=ghcr.io/astral-sh/uv:0.8.21 /uv /uvx /bin/

RUN apk add gcc musl-dev postgresql-dev linux-headers --no-cache

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV UV_PYTHON_DOWNLOADS=0

WORKDIR /app
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project
COPY . /app
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen

FROM python:3.13-alpine AS production

ARG UID=1000
ARG GID=1000

COPY --from=ghcr.io/astral-sh/uv:0.8.21 /uv /uvx /bin/

RUN apk add libpq bash git --no-cache

RUN addgroup -g ${GID} -S devuser && adduser -u ${UID} -S -G devuser devuser

COPY --from=builder --chown=devuser:devuser /app /app

RUN chmod +x /app/entrypoint.sh

ENV PATH="/app/.venv/bin:$PATH"

USER devuser

WORKDIR /app

EXPOSE 8000